Gemfile
Gemfile.lock

Update gems to point to GitHub instead of local copies.

Point scraper gems to GitHub

---

Gemfile
Gemfile.lock
README.md
app/models/instagram_post.rb
app/models/tweet.rb
app/uploaders/video_uploader.rb
app/views/archive/_item_media_preview.html.erb
app/views/instagram_users/show.html.erb
app/views/twitter_users/show.html.erb
config/initializers/shrine.rb
db/migrate/20210628185327_create_twitter_video_preview.rb
db/schema.rb
test/models/instagram_post_test.rb
test/models/tweet_test.rb

Generate video preview images whenever a video is uploaded.
This is covered in tests, but you can also view the home page and see the `poster` attribute to a `video` tag.
Closes #50

Generate video preview image

---

README.md

When using rbenv, installing ruby versions with the `--keep` or `-k` flag ensures that Ruby source files are locally available for gems that need them, like `dhash-vips`

Update rbenv installation instructions

---

Gemfile
Gemfile.lock
app/media_sources/instagram_media_source.rb
app/models/sources/instagram_post.rb
app/models/sources/instagram_user.rb
config/initializers/figaro.rb
test/models/instagram_post_test.rb

Due to the fact that Instagram (and probably everyone else) blocks AWS,
Azure, etc. IP addresses we need to run the scraping from somewhere
else. To that end I created a server for it and am running it locally in
my apartment off a Raspberry Pi 3. So this changes the behaviour to call
the server instead of the local version of the gem.
This adds two new required environment variables:
`ZORKI_SERVER_URL` which points to the right server
`ZORKI_AUTH_KEY` which is the auth key for authenticating the requests
Everything else stays exactly the same.
To test:
1. Pull this branch
2. Run `bundle install` since the zorki gem is now removed from the
requirements
3. Add the two environment variable however you're handling that
4. Run `rails t` and it'll pass

Switch from using Zorki locally to external host

---

app/models/archive_item.rb
app/models/media_review.rb
db/migrate/20210913200056_create_media_review.rb
db/schema.rb

This PR adds a basic `MediaReview` model with a few attributes. A `MediaReview` belongs to an `ArchiveItem`, and will eventually be created in the IngestController here: 
https://github.com/TechAndCheck/zenodotus/blob/8d405d89299146dc06c1b9d20a81a1e26e7ada13/app/models/archive_item.rb#L16-L31

Add mediareview model, relations, and db table

---

.rubocop.yml
app/controllers/application_controller.rb
app/controllers/archive_controller.rb
app/controllers/ingest_controller.rb
app/models/archive_item.rb
config/routes.rb
test/controllers/ingest_controller_test.rb
test/models/unified_user_test.rb

This PR enables API users to add to media/ClaimReview objects to the archive by submitting a link to a page in which well-formed MediaReview objects are embedded. 
Currently, I'm testing this by passing in a link to a GithHub page hosted out of one of my repos. At some point, we should probably mock that page out (and hey, unrelated, maybe mock Zorki, too). 
`rails t` 
No migration required
closes #91

Archive embedded MediaReview via URL 

---

app/jobs/scraper_job.rb
app/models/sources/instagram_post.rb
app/models/sources/tweet.rb
test/models/instagram_post_test.rb
test/models/tweet_test.rb

This PR adds a new method, `create_from_url!`, to the `tweet` and `InstagramPost` media models, which spawns an ActiveJob tasked with scraping and archiving a post.
To test:
- Pull this branch
- run `rails t`
Closes #106

Add methods to run scrapers in ActiveJob

---

Gemfile
Gemfile.lock
app/models/sources/tweet.rb
app/views/archive/_item_media_preview.html.erb
db/migrate/20210708172459_create_image_searches.rb
db/migrate/20220203211301_add_type_to_twitter_videos.rb
db/schema.rb
test/models/image_search_test.rb

This PR works in tandem with https://github.com/cguess/birdsong/pull/7, which allows Birdsong to archive and distinguish Tweets containing gifs. 
The PR adds the attribute `video_type` to the `TwitterVideo` model, allowing us to mark gifs in the archive's media previews. E.g.: 
Closes #116 
1. `rails db:migrate`
2. `bundle install`
3. `rails t`
We should merge https://github.com/cguess/birdsong/pull/7 before merging this PR. After that happens, we should change the Gemfile on this branch to point to `birdsong/master` instead of `birdsong/archive-gifs`

Distinguish GIFs from other twitter videos

---

Gemfile.lock
app/models/sources/facebook_post.rb
app/models/sources/instagram_post.rb
test/models/facebook_post_test.rb
test/models/facebook_user_test.rb
test/models/instagram_post_test.rb
test/models/instagram_user_test.rb

This PR updates Zenodotus to comply with Hypatia's new return schema. Posts are nested one level down from where we used to expect them.  
It also corrects a sorbet type mistake. All tests should pass once this goes in!
`rails t`

Fix Hypatia integration, sorbet types, and tests

---

db/migrate/20210708172459_create_image_searches.rb
db/migrate/20220103202619_add_user_to_image_searches.rb
db/migrate/20220302174537_add_user_reference_to_image_searches.rb
db/migrate/20220303150343_add_user_foreign_key_to_text_searches.rb
db/schema.rb

Long ago in a galaxy not so far from our own, I retroactively edited a database migration. Bad idea. In editing the old migration, I referenced a table created by a future migration, which effectively nuked the migration history chain.
In this PR, I undo my edit to the old [migration](https://github.com/TechAndCheck/zenodotus/blob/8b601562f16aa286338e795beab0060aa841aa5d/db/migrate/20210708172459_create_image_searches.rb) and copy its changes into [a new migration](https://github.com/TechAndCheck/zenodotus/blob/8b601562f16aa286338e795beab0060aa841aa5d/db/migrate/20220302174537_add_user_reference_to_image_searches.rb). This fixes the migration history chain. 
1. Merge https://github.com/TechAndCheck/zenodotus/pull/148 or cherry-pick its changes into this branch
1. `rails db:drop`
2. `rails …

remediate past migration sins

---

app/controllers/jobs_status_controller.rb
app/views/jobs_status/index.html.erb
db/schema.rb
test/controllers/jobs_tracker_controller_test.rb

Instead of using `.last` to get the url being scraped we explicitly use the array index.

Clean up job status

---

app/controllers/twitter_users_controller.rb

The method sig for `TwitterUsersController.export_tweeter_data` had a typo, and consequently the method would throw an error. This PR repairs that.
**To test:**
1. Before pulling this code, run the app and navigate to a Twitter user's page (e.g. a URL rooted at `/twitter_users`) and click on the download arrow next to "Archived Media Items". This should ❌ fail.
2. Pull this code.
3. Do the same thing. Now the download should ✅ succeed.
Closes #161

Fix method signature for Twitter user data export

---

app/controllers/archive_controller.rb
app/jobs/scraper_job.rb
app/media_sources/facebook_media_source.rb
app/media_sources/media_source.rb
app/media_sources/twitter_media_source.rb
app/models/sources/facebook_post.rb
app/models/sources/instagram_post.rb
test/controllers/archive_controller_test.rb
test/models/tweet_test.rb

This fixes a few little bugs that caused some broken tests when scraping
primarily facebook and twitter. Why this happened when we though we had
fixed it awhile ago? Unsure.
However, all tests should fully pass after this.
To test:
`rails t`

Fix a bunch of type errors between Hypatia

---

app/media_sources/facebook_media_source.rb
test/media_sources/facebook_media_source_test.rb

When not forcing a request to a `FacebookMediaSource` we had a bug in
the typing that would mean it would always error out. Whoops. There
didn't seem to be a test for this either. I've fixed both.
To test
`rails t test/media_sources/facebook_media_source_test.rb`

Fix type issue when extracting from facebook

---

config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/sidekiq.yml

This PR prefixes Active Job queue names with `zenodotus_{environment}` to avoid queue collisions when Zenodotus is being run on the same machine as another Sidekiq-using app (like Hypatia locally).
To test:
🚨 Pay particular attention to the fact that I enabled prefixes in production, too. You may not want this! But I figured, hey, why not.
Closes #171

Prefix Active Job queues with Zenodotus namespace

---

app/media_sources/facebook_media_source.rb
app/media_sources/instagram_media_source.rb
config/initializers/figaro.rb
docs/DEVELOPMENT.md

This PR removes the `ZORKI_AUTH_KEY`/`FORKI_AUTH_KEY` and `ZORKI_SERVER_URL`/`FORKI_SERVER_URL` environment variables and replace them with `HYPATIA_AUTH_KEY`/`HYPATIA_SERVER_URL`. 
It also updates `config/intializers/figaro.rb` to require the presence of all of Zenodotus' environment variables. 
Changes are documented in the developer README.
- `rails t`
_Note: before testing, make sure you've set all environment variables. Before merging this PR, we may need to create a shared Tech&Check YouTube API key._

Condense environment variable list

---

Gemfile.lock
app/models/archive_item.rb
app/models/concerns/dhashable.rb
app/models/image_hash.rb
app/models/image_search.rb
app/models/media_models/images/facebook_image.rb
app/models/media_models/images/instagram_image.rb
app/models/media_models/images/twitter_image.rb
db/migrate/20220420175054_create_image_hashes.rb
db/migrate/20220422194316_drop_dhash_from_image_models.rb
db/schema.rb
test/fixtures/image_hashes.yml
test/models/facebook_post_test.rb
test/models/image_hash_test.rb
test/models/instagram_post_test.rb
test/models/tweet_test.rb

This add hashing of video previews and restructures where hashes live to make it easier to index later on.
On the front end you won't notice anything different, as it's all reflected in data structures.
To test:
bundle install
rails db:migrate
rails t

Implement video hashing

---

Gemfile
Gemfile.lock

This PR switches our installation of the Eikon gem from @cguess's own repo to RubyGems, and updates it to 0.1.1.
This should resolve the CI failures we've been seeing.

Install Eikon from RubyGems and update to 0.1.1

---

package.json

I accidentally added two (of our three) Tailwind plugins as dev dependencies, oops. This PR puts them back in the normal dependency stack.
No related issue.

Move Tailwind plugins to correct dependency block

---

LICENSE
README.md

This PR adds the MIT license to the repo and references it in our README.
**Testing:**
- Fork the project
- Make and sell a commercial version of it
- Convince us to sue you
- Win in court because this license permits that
Closes #199

Add MIT license to project

---

app/assets/stylesheets/application.tailwind.css
app/views/layouts/_footer.html.erb
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb
tailwind.config.js

This PR begins the layout redesign with some pretty small steps, redesigning the header (both aesthetically and functionally) and adding a very minimal footer. I should note that I'm not ecstatic with the behavior of the mobile menu and will improve that in the future.
It also does a few cleanup odds and ends, like removing the Google Font stack from the header (if we want to play with the font stack later, I'll include them in the repo so we aren't loading from Google) and disables Tailwind's class-shaking bundle minimization when running in development (since it was so aggressive that it wasn't letting me use any new classes without manually clobbering/recompiling).
**Before → After:**
_(Ignore the apparent shadow on the left part of the image, that's an unnoticed shadow from my Dock.)_ …

Reskin header and add footer

---

tailwind.config.js

This PR removes the `safelist` hack added in bbfdb5b3bc480c19d2bdd2e2a6d8a9f08aac4a92 for reasons explained in the commit message. In summary: I'm no longer seeing the behavior the hack was intended to fix, and it's probably the wrong way to do it anyway.
Not gonna worry about a review on this one, just passing it through PR for history.

Remove Tailwind safelist hack

---

config/environments/production.rb

Deplying on Heroku was failing because of the `purge` css compressor
being run by default. I'm not sure what that is, if that's an issue
@reefdog let me know.

Remove CSS preprocessor from production for heroku

---

app/media_sources/youtube_media_source.rb
test/models/youtube_post_test.rb

This PR resolves our ability to scrape YouTube through the queue by fixing the method sig on the `YoutubeMediaSource#retrieve_youtube_post` method. It also updates the test that actually calls this method to be sure we catch it in the future..
**Failing preconditions:**
Before pulling/testing this branch, if you try to run archive a YouTube URL (either through the web interface or through the console using `Sources::YoutubePost.create_from_url "{url}"`, **note the lack of a `!` on the method name**), the scrape would essentially loop indefinitely, so you'd see multiple copies of the scrape until you shut things down.
**Testing:**
- Fire up Zeno app and archive a YouTube URL through the web interface, **or** fire up the Zeno console and archive via `Sources::YoutubePost.create_from_url …

Repair the retrieve_youtube_post method sig

---

Gemfile
Gemfile.lock

This PR pins us to Sidekiq `~> 6.4.1` (resolving to 6.3.2 currently) in order to get us the fix for very noisy Redis deprecation notices from https://github.com/mperham/sidekiq/pull/5139.
Before this PR, your Sidekiq console is often full of deprecation notices. After this PR, it should be a clean and sparkling place of mostly nothing, like a fancy jacket store.
**To test:**
- 🚨 `bundle install`
- Fire up Sidekiq (of course)
- `rails t`
Closes #176

Upgrade Sidekiq to 6.4.2

---

.eslintrc
package.json
yarn.lock

Our existing ESLint was out of date and showing parsing errors when using out-of-the-box Stimulus. It was also very React-focused, which we aren’t using. This PR:
- Upgrades ESLint and ESLint-related packages we are using
- Removes the packages we aren’t using
- Converts us from the React-focused `airbnb` plugin to the React-free `airbnb-base` plugin
- Removes React/JSX-related rules
**Testing:**
- **Before installing**, run `eslint app/javascript/controllers/image_search_controller.js`
- ❌ Note that you get a parsing error
- `yarn install`
- Lint that same file
- ✅ Note that you get eight errors, which are actual lint errors
Closes #227

Upgrade ESLint and clean up config

---

app/assets/stylesheets/application.tailwind.css
app/assets/stylesheets/archive_items.css
app/assets/stylesheets/author_archives.css
app/assets/stylesheets/authors.css
app/assets/stylesheets/buttons.css
app/assets/stylesheets/variables.css
app/controllers/facebook_users_controller.rb
app/controllers/instagram_users_controller.rb
app/controllers/twitter_users_controller.rb
app/controllers/youtube_channels_controller.rb
app/helpers/application_helper.rb
app/models/sources/facebook_post.rb
app/views/archive/_archive_item.html.erb
app/views/facebook_users/show.html.erb
app/views/instagram_users/show.html.erb
app/views/twitter_users/show.html.erb
app/views/youtube_channels/show.html.erb
config/routes.rb

This PR significantly redesigns the user pages.
**Before:**
**After:**
⚠️ The "After" screenshot shows a masonry-style layout that actually only works (1) in Firefox and (2) after enabling an experimental feature. :( You'll likely actually see a slightly different and less compact layout.
**Testing:**
- Scan the code, how's it look? Sensible?
- `./bin/dev`, go to the Most Recent Archived Items page, and click on the author.

Redesign user pages

---

app/controllers/archive_controller.rb

This PR hotfixes the archive index to only return the most recent 50 items, because otherwise it shows the entire index. This slows the page way down.
We need to [add pagination](https://github.com/TechAndCheck/zenodotus/issues/241), but this will be a stopgap until then.

Hotfix: Limit archive index to 50 items

---

Gemfile.lock
app/models/sources/facebook_post.rb
app/views/text_search/_search_result_facebook_post.html.erb
test/models/facebook_post_test.rb

- Add helper methods to access Facebook reaction counts. 
- Correct attribute paths in Facebook views
test: `rails t`

Hotfix Facebook views

---

app/views/archive/_item_media_preview.html.erb
app/views/text_search/_search_result_facebook_post.html.erb
app/views/text_search/_search_result_instagram_post.html.erb
app/views/text_search/_search_result_tweet.html.erb
app/views/text_search/_search_result_youtube_post.html.erb

The current text search result views in `master` don't render video preview images. This PR resolves that 
Testing
1. load image and video posts from each of the sources
2. Search for text in the posts
3. See preview images
NOTE: I can't log into Instagram right now, so I wasn't able to test media from the platform

Properly render media previews in search results

---

lib/tasks/users.rake

Previously, we compared each facebook user to all other users with the same facebook id, then deleted them. Unfortunately, we compared users to themselves and ended up deleting all users. Now we don't!
```
rails users:dedup_facebook
```

Fixes bug in Facebook user deduplication script

---

app/models/scrape.rb

This PR adds complete type signatures to the `Scrape#initialize` and `Scrape#fulfill` methods. (Please verify that these signatures are correct! I'm going on my own assumptions here.)
**Testing:**
1. On `master`, run `rails t test/controllers/archive_controller_test.rb`. It should ❌ fail with a complaint about the method type signature.
2. On `248-add-scrape-sigs`, run that test again. It should ✅ succeed (or at least, fail somewhere different than on type sigs).
Resolves #248

Provide proper type signatures to Scrape methods

---

app/views/layouts/_header.html.erb
config/routes.rb

This PR just hides some of the in-progress parts of the site so people demoing it don't stumble into unusable areas. Mostly, it suppresses the account signup screens that Devise auto-provides that don't actually do anything yet. This is all somewhat temporary until we actually finish out #153.
There's a bit of redirection duct tape in the routes file that I'm not keen on, but I got tired of trying to dig out Devise's guts.
**Testing:**
- Run the app to make sure logging in/out and changing user settings still works
- Run tests; I was getting inconsistent results that worry me a bit but I think it was specific to my machine?

Hide unused user routes and pages

---

app/models/sources/youtube_post.rb

Youtube video preview images weren't being downloaded via AWS when sent
in that way. This fixes that up and returns to expected use.
To test:
`rails t test/models/youtube_post_test.rb`
closes #260

Download video preview images from AWS

---

app/jobs/application_job.rb
app/media_sources/facebook_media_source.rb
app/media_sources/instagram_media_source.rb
app/media_sources/youtube_media_source.rb

Note: This is based off of PR #291 so do that first.
We were creating scrapes, but if there was an error raised by
a media_source we weren't marking the scrapes as errored. Whoops.
To test:
- Make sure Hypatia isn't connected
- Submit a new url
- While watching the job status page only one should should up

Mark Scrapes as Errored When They Are

---

app/views/archive/_archive_item_media_inline_full.html.erb

This PR disables video preloading, which happens automatically under certain browser/bandwidth conditions. With preloading allowed, then the browser would sometimes skip the poster and just download the full video; it's not clear what these conditions were, but it's possible we hit a timeout on the `poster` download and so triggered the preload-for-metadata process.
Now, we set`preload="none"` on all `<video>` elements to ensure the browser doesn't begin downloading the videos until the user actually plays the video. This is preferable anyway for us since we are usually showing multiple (sometimes very many) videos per page, with no confidence the user is likely to play any of them, but it should also ensure the browser waits around for the poster image and doesn't try to fetch the video …

Improve video embedding

---

app/assets/stylesheets/forms.css
app/assets/stylesheets/variables.css
app/controllers/applicants_controller.rb
app/helpers/applicants_helper.rb
app/helpers/form_helper.rb
app/models/applicant.rb
app/views/applicants/new.html.erb
app/views/applicants/thanks.html.erb
app/views/layouts/_header.html.erb
app/views/partials/_errors_for_field.html.erb
app/views/users/sessions/new.html.erb
config/initializers/terms_of_service.rb
config/routes.rb
db/migrate/20220808225818_create_applicants.rb
db/schema.rb
test/controllers/applicants_controller_test.rb
test/fixtures/applicants.yml
test/models/applicant_test.rb

This PR adds the Request Access page to the site. It's not full-featured, as it doesn't yet require email confirmation or allow the user to close the loop on creating a user account, but it's the first step.
**Testing:**
- Run the migrations
- Check tests with `rails t test/models/applicant_test.rb`
- Start the app with `./bin/dev`
- Go to the "Request access" link in the navbar
- Fill out the application and submit
**Notes:**
- I used the `required` attribute on fields that are required, which means the browser will stop the user from submitting a form without them. You can flip them to `required: false` to see Rails validation in action.
- The "Thanks" page is unstyled. That's because it's going to quickly be replaced with the "You must confirm your email" page anyway.
- The language is …

Add Request Access page

---

Gemfile
Gemfile.lock
app/controllers/applicants_controller.rb
app/views/applicants/new.html.erb
db/migrate/20220830181411_add_country_to_applicant.rb
db/schema.rb
test/fixtures/applicants.yml

This PR adds the Country field to the Request Access application form, as "Where are you located?":
To do so, it uses the [`country_select`](https://github.com/countries/country_select) gem.
**Testing**
- 🚨 `bundle install`
- 🚨 `rails db:migrate`
- Run tests: `rails t test/models/applicant_test.rb`
- Start the app and go to the Request Access page. Make sure you can create an applicant both with and without a country selected. Wouldn't hurt to check the database manually to be sure `country` contains the expected country code.
Closes #323

Add country to application form

---

app/models/applicant.rb
app/views/applicants/new.html.erb
test/models/applicant_test.rb

This PR makes the "How do you plan to use the data?" field on the Request Access form required, and moves it to be with the other required fields:
As shown there, it also adds the "required" asterisk to the "Accept the terms and conditions" checkbox, which was already required functionally.
**Testing:**
- Make sure you can't submit the form without entering a use case (stretch testing: disable `required: false` in the HTML template to trigger the Rails validation)
Closes #324
Closes #326

Make "use case" field required on Request Access form

---

test/models/applicant_test.rb

This PR does a tiny bit of work toward #328 by replacing an `assert_nothing_raised` test on the `Applicant` model with a standard assertion. See the related issue for some of the reasoning.
**Testing:**
- `rails t test/models/applicant_test.rb`
Affects #328

Remove assert_nothing_raised applicant test

---

app/models/applicant.rb
test/fixtures/applicants.yml
test/models/applicant_test.rb

This PR makes some minor changes to our `Applicant` fixtures (and some model comments), basically some tidying up in preparation for future changes in #271.
- Renames the too-cute `jane` fixture to simply `new` to match its role as a fresh new applicant
- Removes unused optional attributes from fixture until we need them (to cut down on boilerplate)
- Improves the wording of some `Applicant` model method descriptions
This is a lightweight PR that I'm going to merge myself without approval.

Improve applicant fixtures

---

app/controllers/accounts_controller.rb
app/models/user.rb
config/initializers/devise.rb
config/routes.rb

This PR enables email confirmation for users changing their email address. This is a necessary prerequisite for cleanly converting applicants (which require confirmed emails) to users, and is good form besides.
**Testing:**
- Start Rails and Sidekiq
- Log in and go to your user settings screen (http://localhost:3000/account)
- Update your email address to a new one (that you actually have access to)
- ✅ See a flash that tells you to go check your email
- ✅ Verify (in console/database) that your email has not _actually_ changed yet
- Go check your email! Click the confirmation link inside. (Ignore the email design and language. This is Devise boilerplate that we will customize.)
- ✅ Clicking the link should confirm the email change; verify in console/database
Issue #271

Enable change-of-email confirmation for users

---

app/models/applicant.rb
app/models/user.rb
db/migrate/20220912215054_add_user_to_applicants.rb
db/schema.rb
test/models/user_test.rb

_This PR ladders off #343._
This PR adds the ability to create a user given an approved applicant. It's step 2 on our way to #271.
⚠️ Note that you won't be able to actually log in as this user just yet (unless you are very good at guessing passwords). The next PR will add the notification email to the user and the ability for them to change their password.
**Testing:**
- Prerequisite: A **new applicant** whose email **has been confirmed,** and which email **doesn't match an existing user**.
- 🚨 `rails db:migrate`
- ✅ `rails t`
- `rails c`
- Find the prerequisite applicant: `a = Applicant.find(id)`
- Create the accompany user: `u = User.create_from_applicant(a)`
- ✅ It should work! (Though see ⚠️ note above.)
- Destroy the user: `u.destroy`
- ✅ The original applicant **should be …

Create a user from a given applicant

---

test/models/facebook_post_test.rb

Closes https://github.com/TechAndCheck/zenodotus/issues/334
In `FacebookPostTest.can_create_Facebook_post_test`, we use `assert_equal` to compare two null attributes (the post in the example has no text)
https://github.com/TechAndCheck/zenodotus/blob/20047363bba63f3c5a7bc02455fafa40fbabe791/test/models/facebook_post_test.rb#L30
This prompts a MiniTest warning: 
```
DEPRECATED: Use assert_nil if expecting nil from test/models/facebook_post_test.rb:30. This will fail in Minitest 6.
```
This PR changes the comparison. 
`rake`

Remove `assert_equal` comparison for nil values in FacebookPostTest

---

app/models/sources/youtube_post.rb
test/mocks/data/youtube_posts.json

This PR moves some duration attribute formatting logic out of Zenodotus and into the `YoutubeArchiver` scraper gem. 
See https://github.com/TechAndCheck/YoutubeArchiver/pull/10. Closes https://github.com/TechAndCheck/zenodotus/issues/341
`rake`

Move YoutubePost duration conversion out of Zenodotus

---

app/controllers/application_controller.rb

I wasn’t aware of `redirect_back_or_to` when I wrote my convoluted `ApplicationController#must_be_logged_out` method, despite it being used literally in that same file. Fun!
This quick fix makes use of it. It is caught by a test (`rails t test/controllers/accounts_controller_test`), so run that and make sure it's clean.
There's no accompanying issue, it's just a quick thing I noticed.

Improve the must_be_logged_out redirection

---

.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/accounts_controller.rb
app/controllers/application_controller.rb
app/models/role.rb
app/models/user.rb
app/views/layouts/_header.html.erb
config/initializers/rolify.rb
db/migrate/20220919194501_rolify_create_roles.rb
db/migrate/20220919214503_convert_admins_to_rolify.rb
db/schema.rb
db/seeds.rb
docs/ARCHITECTURE.md
test/controllers/accounts_controller_test.rb
test/controllers/archive_controller_test.rb
test/controllers/jobs_tracker_controller_test.rb
test/controllers/text_search_controller_test.rb
test/fixtures/api_keys.yml
test/fixtures/roles.yml
test/fixtures/users.yml
test/helpers/accounts_helper.rb
test/models/api_key_test.rb
test/models/archive_item_test.rb
test/models/image_search_test.rb
test/models/role_test.rb
test/models/user_test.rb

This PR adds the concept of user roles to the site, and converts our determination of "what is an admin?" to use it.
It adds the Rolify gem (as determined in #282), which lets us add roles ad-hoc both "globally" (applies to the user everywhere) and per-resource (e.g. "user can moderate this particular archive item"), although we're only using the global roles. Roles are non-exclusive; a user can have multiple roles at once.
We currently have four roles:
- `new_user` is assigned during `User` creation, and it semantically means "this user has not yet completed their setup process". This role is removed when the user follows the link in their email and chooses their password.
- `insights_user` is also assigned during `User` creation, and it semantically means "this user is approved to use …

Add user roles

---

app/controllers/archive_controller.rb

Our manual archive button currently executes the `ActiveJob` flow, which expects that:
1. An orphaned `MediaReview` item will be created
2. We'll scrape Hypatia and create an `ArchiveItem`
3. We'll attach the orphaned `MediaReview` to the newly created `ArchiveItem`
But step 1 only happens if we either manually create a `MediaReview` item or receive one from FactStream (which happens in production).
Since no one but the dev team uses the "add to archive button", we can change it to skip the `ActiveJob` MediaReview fulfillment flow and just create an `ArchiveItem`.
Closes https://github.com/TechAndCheck/zenodotus/issues/360

Use the non-`ActiveJob` flow when the "add to archive" button is clicked

---

app/controllers/application_controller.rb
app/controllers/archive_controller.rb
app/controllers/facebook_users_controller.rb
app/controllers/image_search_controller.rb
app/controllers/instagram_users_controller.rb
app/controllers/jobs_status_controller.rb
app/controllers/login_controller.rb
app/controllers/settings_controller.rb
app/controllers/twitter_users_controller.rb
app/controllers/users/sessions_controller.rb
app/controllers/youtube_channels_controller.rb
app/views/users/sessions/new.html.erb
config/routes.rb
test/controllers/applicants_controller_test.rb
test/controllers/facebook_users_controller_test.rb
test/controllers/image_search_controller_test.rb
test/controllers/instagram_users_controller_test.rb
test/controllers/jobs_status_controller_test.rb
test/controllers/sessions_controller_test.rb
test/controllers/text_search_controller_test.rb
test/controllers/twitter_users_controller_test.rb
test/controllers/youtube_channels_controller_test.rb
test/fixtures/sources/facebook_users.yml
test/fixtures/sources/instagram_users.yml
test/fixtures/sources/twitter_users.yml
test/fixtures/sources/youtube_channels.yml
test/fixtures/twitter_users.yml

This PR locks down all routes that need locking down, ensures the ones that need to be open are open, and adds tests to catch as much of this as possible.
I opened #166 after noticing that I could hit pages I wasn't supposed to be able to, such as a Twitter user page while logged out, or a Jobs status page while logged in as a user (not admin). Now, all pages should be locked down correctly.
It looks like a huge PR, but a ton of it are just new tests. That said, a lot of controllers were touched (and unused ones removed), so feel free to comb through.
⚠️ Note that the commits are organized sensibly, so it might be preferable to go through each commit individually since the description may provide relevant change context.
**Testing:**
- `rails t` obviously
- I highly recommend doing a full …

Fix authentication on all controller methods

---

app/controllers/applicants_controller.rb
app/models/applicant.rb
test/controllers/applicants_controller_test.rb
test/models/applicant_test.rb

_This PR ladders off #359._
This PR closes a loophole that would let people apply using an existing users' email address by changing the casing. (Of course, they'd not have been able to close the loop on becoming a user since they'd hit our uniqueness restrictions during the user-creation process, but this stops them a lot earlier.)
Note that it does the downcasing in two places:
1. As part of a `before_save` action on the model itself; this keeps it out of the database entirely. I could have done this via `after_initialize` so that `Applicant.new` would have it, but I wanted that to represent the user's input until the actual save point.
2. As part of the check for existing users in the controller action. Here I could have changed the casing while passing the params to `Applicant.new`, …

Lowercase applicant emails for better matching against users

---

app/controllers/archive_controller.rb
app/controllers/facebook_users_controller.rb
app/controllers/instagram_users_controller.rb
app/controllers/twitter_users_controller.rb
app/controllers/youtube_channels_controller.rb
app/models/archive_item.rb
app/views/facebook_users/show.html.erb
app/views/instagram_users/show.html.erb
app/views/twitter_users/show.html.erb
app/views/youtube_channels/show.html.erb
config/routes.rb
test/controllers/facebook_users_controller_test.rb
test/controllers/instagram_users_controller_test.rb
test/controllers/twitter_users_controller_test.rb
test/controllers/youtube_channels_controller_test.rb

This PR cleans up how we're generating the JSON export file for our authors. Previously, it was a separate route from the `show` action with its own nearly-identical-but-not-quite query.
Now, it's all within `show` and performs the same query, but customizes the generation based on format requested (HTML v. JSON). It also removes the now-unused routes and adds tests of the JSON generation.
This came out of looking at #235, which was already fixed, but this makes it even more fixed. Fixeder.
**Testing:**
- You may have to `bundle install` depending on previous setup
- `rails t` of course
- Run the app and go to the author pages for each type (Twitter, Instagram, Facebook, and YouTube)
- ✅ Make sure the JSON download button… downloads JSON!
Closes #235

Simplify author JSON export

---

config/routes.rb

b7df27d3d8fb1f54f8a7b2f4e06241da81ba6dd8 intentionally namespaced the MV-related routes under `media_vault`, but this was meant to prefix the helpers (`media_vault_foo_bar_url`) and the controllers (`MediaVault::FooController`). It was _not_ intended to insert `media_vault/` into each path, which the `namespace` approach does.
This PR fixes that by using `scope` instead.
**Testing:**
- `rails t` (of course)
- Start the app, log in, and click "Text Search". The URL should just be `{hostname}/text_search`. If it is `{hostname}/media_vault/text_search`, then things are still screwy.
Issue #301

Fix MediaVault routes to remove `media_vault` path

---

README.md
app/controllers/application_controller.rb
app/controllers/fact_check_insights_controller.rb
app/helpers/application_helper.rb
app/helpers/fact_check_insights_helper.rb
app/views/fact_check_insights/index.html.erb
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb
app/views/layouts/fact_check_insights/_footer.html.erb
app/views/layouts/fact_check_insights/_header.html.erb
app/views/layouts/media_vault/_footer.html.erb
app/views/layouts/media_vault/_header.html.erb
app/views/media_vault/index.html.erb
config/application.rb
config/environments/development.rb
config/initializers/session_store.rb
config/routes.rb
docs/DEVELOPMENT.md
test/controllers/fact_check_insights_controller_test.rb
test/controllers/media_vault/archive_controller_test.rb
test/controllers/media_vault/facebook_users_controller_test.rb
test/controllers/media_vault/image_search_controller_test.rb
test/controllers/media_vault/ingest_controller_test.rb
test/controllers/media_vault/instagram_users_controller_test.rb
test/controllers/media_vault/text_search_controller_test.rb
test/controllers/media_vault/twitter_users_controller_test.rb
test/controllers/media_vault/youtube_channels_controller_test.rb

🚨 **This is a PR with big consequences!**
Prior to this PR, things were nice and easy, as the entire app was hosted at a single domain. Locally, you could just fire up `http://localhost:3000` and be merry. Given our desired architecture, though, we want the app to appear as "Fact-Check Insights" when accessed via `www.factcheckinsights.org` and as "MediaVault" when accessed via `vault.factcheckinsights.org`. (They're both rooted at the same domain for session-sharing ease.)
Starting with this PR, we split the entire experience based on which subdomain you're using. While we fall back to the Insights experience (so `localhost` technically still works), if you want to see the MediaVault stuff — which is currently most of the site — you'll need to change your local setup.
- **To run …

Serve Vault and Insights on discrete domains

---

app/media_sources/facebook_media_source.rb
app/media_sources/instagram_media_source.rb
app/media_sources/media_source.rb
app/media_sources/twitter_media_source.rb
app/media_sources/youtube_media_source.rb
test/media_sources/media_source_test.rb

This PR gives Zenodotus the ability to archive media re-hosted on archive.org 
If Zenodotus receives an Archive request for a media post hosted on archive.org, it will now try to extract the post's original URL and use it to generate a Hypatia scrape request. 
`rake`
Closes #380

Handle archive.org links

---

app/jobs/scraper_job.rb
app/media_sources/media_source.rb
app/media_sources/twitter_media_source.rb

This PR removes the `runs_scraper_locally` method from our `MediaSource` class. 
With Birdsong migrated to Hypatia, Zenodotus no longer does any local scraping. 
Closes issue #386
`rake`

Remove `MediaSource.runs_scraper_locally`

---

app/controllers/application_controller.rb
app/controllers/fact_check_insights_controller.rb
app/controllers/media_vault_controller.rb
app/views/applicants/confirmation_error.html.erb
app/views/applicants/new.html.erb
app/views/application/about.html.erb
app/views/application/contact.html.erb
app/views/fact_check_insights/download.html.erb
app/views/fact_check_insights/guide.html.erb
app/views/fact_check_insights/highlights.html.erb
app/views/layouts/fact_check_insights/_header.html.erb
app/views/layouts/media_vault/_header.html.erb
app/views/media_vault/guide.html.erb
app/views/pages/credits.html.erb
app/views/status/accounts/invalid_token.html.erb
config/routes.rb
test/controllers/media_vault/archive_controller_test.rb
test/controllers/media_vault_controller_test.rb

This PR stubs out all the pages in our architecture, so that we can actually start adding content and design.
**Testing:**
- `rails s`
- Note that both Insights and Vault now have actual pages in the navigation!
- Make sure that the navigation follows the logged in / logged out behavior described [here](https://github.com/TechAndCheck/zenodotus/wiki/Information-Architecture).
- Note that Vault's elements change more significantly that Insights does when logged in.
- Ignore that MediaVault has two search links and an Archive URL that aren't in the architecture. TBD.
- Ignore the drop-down menu design and "profile image v. username" thing. TBD.
- Ignore styling, of course, including the separation of the page links and user links into separate elements.
Closes #377
Closes #335

Create stubs for all pages

---

app/media_sources/facebook_media_source.rb
app/media_sources/instagram_media_source.rb
app/media_sources/twitter_media_source.rb
app/media_sources/youtube_media_source.rb

This PR removes the ability to send a `callback_url` parameter to Hypatia. It's based on conversation with @cguess about how this functionality isn't needed. It means Hypatia will send all callbacks to whatever URL it is locally configured with, and individual requests can't override this.
**Testing:**
- `rails t`
- Test having Zeno send a scrape to Hypatia and be sure it succeeds
Closes #400

Don’t send `callback_url` to Hypatia

---

README.md
app/controllers/applicants_controller.rb
app/controllers/application_controller.rb
app/helpers/application_helper.rb
app/mailers/account_mailer.rb
app/mailers/applicants_mailer.rb
app/mailers/application_mailer.rb
app/views/account_mailer/setup_email.html.erb
app/views/account_mailer/setup_email.text.erb
app/views/applicants_mailer/confirmation_email.html.erb
app/views/applicants_mailer/confirmation_email.text.erb
app/views/layouts/fact_check_insights/_header.html.erb
app/views/layouts/media_vault/_header.html.erb
config/application.rb
config/environments/development.rb
config/initializers/figaro.rb
config/initializers/site_definitions.rb
config/routes.rb
docs/DEVELOPMENT.md
test/controllers/applicants_controller_test.rb
test/controllers/application_controller_test.rb
test/controllers/media_vault/archive_controller_test.rb
test/controllers/media_vault/facebook_users_controller_test.rb
test/controllers/media_vault/image_search_controller_test.rb
test/controllers/media_vault/ingest_controller_test.rb
test/controllers/media_vault/instagram_users_controller_test.rb
test/controllers/media_vault/text_search_controller_test.rb
test/controllers/media_vault/twitter_users_controller_test.rb
test/controllers/media_vault/youtube_channels_controller_test.rb
test/controllers/media_vault_controller_test.rb

This PR replaces the `*_URL` versions of the env vars for our apps (e.g. `http://vault.factcheckinsights.local:3000`) with `*_HOST` versions (e.g., `vault.factcheckinsights.local`). It also removes the assumption/restriction that they fit the `{subdomain}.factcheckinsights.local` pattern.
It also also:
- Removes an unused utility method (`hostname_segments`) that's even less useful now that we aren't following any prescribed hostname format
- Fixes the vestigial name of some methods to change `*_subdomain` to `*_host`
- Makes better use of some existing URL helpers
- Slips in a change to env-var-ify the domain we use for sending email (#401)
**Setup:**
Make the following changes to your ENV vars (`application.yml` or otherwise), substituting whatever hosts you want for the `*_HOST` vars …

Configure apps with host names, not URLs

---

app/controllers/fact_check_insights_controller.rb
app/models/user.rb
app/views/fact_check_insights/download.html.erb

This PR adds the wiring for generating a secure JSON download for users authorized to download Insights data.
- Add `can_access_fact_check_insights?` user method that goes beyond the proxying of “all users are Insights users” to make it explicit
- Add copy to Download page (but without good styling)
- Add JSON endpoint to download page, secured by authorization check, that generates an empty dataset for now.
Issue #275

Stub out Insights data download with empty JSON

---

app/controllers/media_vault/ingest_controller.rb
app/models/scrape.rb

We somehow forgot to update the `scrapes` channel when a scrape is fulfilled. This fixes that.
To test:
Unfortunately the only way to test this is to launch a Hypatia instance and go through the whole thing of scraping and waiting for a callback. The code that's called is already in production use, so maybe we just say "ok" to it ;-)`
Closes #410

Send a notification when a scrape is done

---

app/javascript/controllers/jobs_status_controller.js
app/javascript/controllers/media_vault/archive_controller.js
app/javascript/controllers/media_vault/author_controller.js
config/importmap.rb

This PR should resolve the issue with some JavaScript not loading correctly in production environments.
We weren't importing some files using the correct syntax, and also hadn't added one of our core files to the importmap.
**Prerequisites:**
If you've never run the app locally in production mode before, then you'll have to do a couple of things:
- Set `RAILS_SERVE_STATIC_FILES: "true"` in your `application.yml` or env vars.
- Configure the `production` block of `database.yml` for your setup. I just copied the `development` block and then ran `RAILS_ENV=production rails db:setup`.
**Testing:**
1. On the `master` branch:
1. `rm -r public/assets`
2. `RAILS_ENV=production rails assets:precompile`
3. `RAILS_ENV=production rails s`
4. Load the app in-browser with your development console open …

Resolve JS importing issues in production mode

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/fact_check_insights_controller.rb
app/models/claim_review.rb
app/models/media_review.rb
db/seeds.rb
public/401.html
test/controllers/fact_check_insights_controller_test.rb
test/models/claim_review_test.rb
test/models/media_review_test.rb

This PR adds `MediaReview`/`ClaimReview` data export functionality to Zenodotus. It uses `BluePrinters` specs created per #390 and #391 to generate JSON exports and a new gem, `comma`, to generate CSV exports. 
The CSV exports are a bit hairy, because they're flat representations of nested data. Column names in the CSV use use underscores to denote nested attributes. 
For example, data corresponding to the `reviewRating.ratingValue` attribute will be written to a  column named `reviewRating_ratingValue`. 
Closes #275 
- `bundle` (install `comma`)
- `rake`
- Log into FCI and try out the CSV and JSON data downloads. Make sure the data in the downloaded files matches the data in our `seeds.rb` file. Try loading the download URLs without being logged in. You shouldn't get any data :)

Fact Check Insights exports

---

app/models/media_review.rb
test/models/media_review_test.rb

This PR handles cases in which the `MediaReview.itemReviewd.mediaItemAppearances` attribute is `nil` or an empty array by just returning `nil` for all related attributes in the CSV
`rake`

Update `MediaReview` CSV serializer to handle null attribute

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/colors.scss
app/assets/stylesheets/containers.scss
app/assets/stylesheets/pages/media_vault_guide.scss
app/assets/stylesheets/pages/media_vault_home.scss
app/views/application/contact.html.erb
app/views/fact_check_insights/_optout_instructions.html.erb
app/views/fact_check_insights/download.html.erb
app/views/fact_check_insights/guide.html.erb
app/views/fact_check_insights/optout.html.erb
app/views/layouts/media_vault/_header.html.erb
app/views/media_vault/_optout_instructions.html.erb
app/views/media_vault/archive/index.html.erb
app/views/media_vault/guide.html.erb
app/views/media_vault/index.html.erb
app/views/media_vault/optout.html.erb

This PR delivers the last of the MediaVault copy (Guide) and makes the opt-out instructions consistent across all uses. It also adds the ability to generate an opt-out email with prefilled instructions.
While more design-related stuff will come up, this is enough to deliver #267 and move on to smaller issues.
Closes #267 
Closes #422

Add MediaVault Guide copy and Opt-Out instructions

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/authors.scss
app/assets/stylesheets/pages/admin_applicants.scss
app/assets/stylesheets/tables.scss
app/assets/stylesheets/typography.scss
app/controllers/admin/applicants_controller.rb
app/helpers/admin/applicants_helper.rb
app/javascript/controllers/admin/applicants_controller.js
app/javascript/controllers/index.js
app/models/applicant.rb
app/models/user.rb
app/views/admin/applicants/index.html.erb
app/views/admin/dashboard.html.erb
app/views/media_vault/archive/_archive_item.html.erb
app/views/media_vault/facebook_users/show.html.erb
app/views/media_vault/image_search/_results.html.erb
app/views/media_vault/image_search/index.html.erb
app/views/media_vault/instagram_users/show.html.erb
app/views/media_vault/twitter_users/show.html.erb
app/views/media_vault/youtube_channels/show.html.erb
config/importmap.rb
config/routes.rb
db/migrate/20221104070857_add_reviewer_to_applicants.rb
db/schema.rb
db/seeds.rb
test/controllers/admin/applicants_controller_test.rb
test/models/applicant_test.rb

This PR adds an applicant management page to the admin area that lets admins review new applicants and look at old applicants.
**Testing:**
- `rails db:migrate`
- Fill in some `NULL` values in the `applicants` table with this Rails console command: `Applicant.reviewed.update_all(reviewed_at: Time.now, reviewer_id: User.with_role(:admin).first.id)`
- `./bin/dev` and also run Sidekiq (to send emails)
- While logged out, go to the Request Access page and request access using an email address you can receive email at (and that doesn't already have an account) and then confirm that email address from your inbox.
- Now, log in as an admin and go to the `/admin/applicants` page
- ✅ You should see your application! Decide that you're worthy and click the Approve button.
- ✅ You should receive an …

Add applicant management page

---

app/models/user.rb
db/migrate/20221104200350_change_insights_user_role.rb
db/schema.rb
db/seeds.rb
docs/ARCHITECTURE.md
test/controllers/fact_check_insights_controller_test.rb
test/controllers/media_vault_controller_test.rb
test/fixtures/roles.yml
test/fixtures/users.yml
test/models/user_test.rb

lol.
This PR lets non-admin Insights users download Insights data. The problem is described in the attached issue, but the chosen solution is actually to rename one of our Rolify roles. Consequently, while the seeds have been updated, this PR does add a migration to convert your existing roles without having to reset the database. But **don't run the migration right away**! See testing instructions below.
**Testing:**
1. On `master`, log in as `insights@example.com` (or any other Insights-permitted **non-admin** user)
2. Go to the download page and try to download data
3. ❌ You should receive a 401 unauthorized response
4. Switch to this branch `433-fix-insights-user-role`
5. `rails db:migrate`
6. Repeat the steps above
7. ✅ You should be able to download the data
I also added new tests, …

Fix ability for users to download Insights data

---

app/controllers/media_vault/archive_controller.rb
app/views/layouts/media_vault/_header.html.erb

This PR hides the Add URL navbar item from non-admins, and locks down the routes so that only admins can access them.
**Testing:**
- Log in as `vault@example.com` (or whatever your local Vault-permitted, **non-admin** user is)
- ✅ Note that there is no "Add URL" item in the navbar
- ✅ Try to go to `/archive/add` and get booted back to the home page with a no-no message
- Log in as `admin@example.com` (or any other admin)
- ✅ Note that there is an "Add URL" item in the navbar
- ✅ Click it and/or go to `/archive/add` and make sure you get the form
- You can also attempt to archive a URL (which should work as an admin) but that depends on the rest of your rig being set up for scraping correctly and should work as before anyway.
Closes #441

Only allow admins to use archive URL function

---

app/views/layouts/media_vault/_header.html.erb
app/views/media_vault/_request_access_instructions.html.erb
app/views/media_vault/index.html.erb

In #382, we describe the need for Insights users without Vault access to request Vault access through a more streamlined flow than filling out the entire Request Access form (which would fail as-is anyway, since they already have an account), and allowing admins the ability to grant existing accounts Vault access.
Until we implement that, this PR adds a stand-in process: when an Insights user is logged in and goes to Vault, the Request Access link spawns an email that lets them request access from the admins. It does nothing on the back end at all; an admin currently would have to then ask a developer to grant the access using the console.
While not ideal, this at least gives users _some_ path to express interest, and us a path to collect interest (and take action).
This PR also modifies …

Add ersatz Request Access to MediaVault flow for Insights users

---

app/controllers/media_vault/ingest_controller.rb
app/models/archive_item.rb
app/models/claim_review.rb
app/models/media_review.rb
db/migrate/20221109152113_add_external_unique_id_to_claim_review_and_media_review.rb
db/schema.rb
test/controllers/media_vault/ingest_controller_test.rb

In tandem with [FactStream PR] this PR lets us update `ClaimReview` and `MediaReview` records when we receive revisions to them from `FactStream`. 
We recognize those revisions by storing the new `external_unique_id` attribute `FactStream` attaches to `ClaimReview` and `MediaReview` and using it to see whether we've already stored identically id'd objects. 
1. `rails db migrate` (add indexed `external_unique_id` column to `ClaimReview` and `MediaReview`)
2. `rake`
Closes #449

Enable updates to `MediaReview`/`ClaimReview`

---

app/controllers/accounts_controller.rb

For some reason changing the password resets the users session and logs them out. Now we just programatically log them back in immediately.
To test:
On master branch:
1. Log in with a user
2. Change the password
3. Refresh the page - you'll end up at the log in page
Switch to this branch:
1. Log in with user
2. Change the password
3. Refresh the page - you should stay on the same page
closes #355

Log user in after changing password

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/author_archives.scss
app/assets/stylesheets/pages/media_vault.scss
app/assets/stylesheets/pages/media_vault_guide.scss
app/assets/stylesheets/pages/media_vault_home.scss
app/views/media_vault/facebook_users/show.html.erb
app/views/media_vault/instagram_users/show.html.erb
app/views/media_vault/twitter_users/show.html.erb
app/views/media_vault/youtube_channels/show.html.erb

This PR fixes a few things that had bugged me (or needed fixing) in MediaVault:
- Fixed the spacing between elements on author show pages (present since we started yielding page content directly into a grid wrapper in the application layout)
- Fixed spacing on the author archive title
- Defaulted all MediaVault pages to have creamy backgrounds (vs white) for more pleasant readability
- Defaulted all MediaVault pages to use a sans-serif typeface, with serif restored for very "designed" pages and long content pages
No issue, just odds and ends.

Fix some MediaVault-related styles

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/buttons.scss
app/assets/stylesheets/pagination.scss
app/controllers/media_vault/archive_controller.rb
app/views/media_vault/archive/index.html.erb

This PR finally adds pagination to the MediaVault dashboard, locked to 50 items per page. It also adds generic pagination styling, applied to the generic Pagy markup and so automatically picked up by other places (like on the search history w/in user settings):
**Testing:**
1. If you have fewer than 50 items in your local vault, then either add more (lol) or temporarily modify [`ARCHIVE_ITEMS_PER_PAGE`](https://github.com/TechAndCheck/zenodotus/blob/0c11eb4853c2fe42f7cf94b63e545598c77e06f4/app/controllers/media_vault/archive_controller.rb#L12) to be less than your archive size.
2. Load up the Dashboard and scroll to the bottom.
3. ✅ Pagination should appear and should be usable!
Note: This will be added to search results soon as they are further beautified in #364.
Closes #241

Paginate MediaVault dashboard

---

app/models/image_search.rb
app/views/media_vault/image_search/_search_result_list_item_facebook_post.html.erb
app/views/media_vault/image_search/_search_result_list_item_instagram_post.html.erb
config/initializers/zelkova.rb

This dedups the search algorithm and returns the best matching frame. It then follows up with making Facebook and Instagram results properly manage videos vs images.
To test:
- Do a media search with something that's in the archive from either Facebook or instagram, then do the other (to guarantee that there's a result in the listing)
- That's about it, nothing will appear if there's an error because the JS throws a 500, if things do appear it works.
closes #459

Fix video searching

---

config/initializers/figaro.rb
config/initializers/shrine.rb

Realistically we only should use one of two S3 buckets for reading Zeno assets. That said, they should still be configurable as env vars rather than hard-coded.
This PR adds a requirement that you have the `AWS_S3_BUCKET_NAME` env var set (if you have S3 enabled), and uses it.
**Testing:**
1. Add the `AWS_S3_BUCKET_NAME` env var (set to `"zenodotus-testing"` locally)
2. `rails t` (make sure `USE_S3_DEV_TEST` is set to true during this test)
3. If you want to go further, import the SQL dump @cguess posted in Slack and make sure archived assets still work
Note: I've already added `AWS_S3_BUCKET_NAME` to staging on Heroku.
Related to issue #205

Make Zeno S3 bucket configurable

---

app/views/media_vault/archive/index.html.erb

This PR wraps the Dashboard items in white boxes, just like they appear elsewhere.
**Before:**
**After:**
Closes #472

Display archive items on Dashboard in boxes

---

app/assets/stylesheets/archive_items.scss
app/javascript/controllers/media_vault/archive_controller.js
app/views/media_vault/media/_archive_item.html.erb

_This PR ladders off #461._
This PR fixes the issue with expand/collapse caption links not working. This was because when I nested the JS within the MediaVault namespace, some of the attributes that needed changing didn't get changed.
Closes #468

Fix expand/collapse caption JS

---

app/mailers/new_applicant_alert_mailer.rb
app/models/applicant.rb
app/views/new_applicant_alert_mailer/new_applicant_email.html.erb
test/mailers/new_applicant_alert_mailer_test.rb
test/mailers/previews/new_applicant_alert_mailer_preview.rb
test/models/applicant_test.rb

After an applicant confirms their email address send an email to all admins (maybe later we want to be able to designate a single contact) alerting them, and pointing them to the right pages.
To Test:
1. Make sure the app and sidekiq are running
2. Make sure you're logged out and apply
3. You'll get an email asking for confirmation to your email. Go ahead and answer it. Or, go into the console and call `.confirm` on the applicant
4. Check sidekiq and you should see the email printed out in the log (since our admins emails point to `example.com` you won't really receive the email itself.
5. Try this in Vault and Insights)
Closes #436

Send email to admins when an applicant applies

---

app/blueprints/media_review_blueprint.rb
app/controllers/media_vault/ingest_controller.rb
app/models/archive_item.rb
app/models/media_review.rb
config/database.yml
public/json-schemas/claim-review-schema.json
public/json-schemas/media-review-schema.json
test/controllers/media_vault/ingest_controller_test.rb
test/models/archive_item_test.rb
test/models/media_review_test.rb

This finalizes (as of now) JSON export of MediaReview, and cleans up
a bunch of tests around the same that was going sideways.
The old methods were correct for the published standard but the
published standard is quite out of date by now, so there had to be
a bunch of updates. This allows FactStream to properly throw MediaReview
at the Zeno instance and for Zeno to know what its getting.
To Test:
Honestly, just run the tests. The testing around the FactStream import
is a complicated setup and really not worth it at the moment.
Closes https://github.com/TechAndCheck/zenodotus/issues/482

Update Everything For Proper MediaReview Export

---

app/assets/stylesheets/archive_items.scss
app/controllers/media_vault/archive_controller.rb
app/controllers/media_vault/authors_controller.rb
app/controllers/media_vault/media_controller.rb
app/models/archive_item.rb
app/views/media_vault/media/_archive_item.html.erb
config/routes.rb
test/controllers/media_vault/media_controller_test.rb

This PR adds a download link to individual media pages, allowing for the export of metadata for lone pieces of media (see below). 
Closes #481 
- `rake`
- Log in to MediaVault, navigate to the dasbhoard, and try clicking a media item's download link

Add download link to individual media pages

---

app/controllers/media_vault/archive_controller.rb
app/controllers/media_vault/ingest_controller.rb
app/jobs/scrape_callback_job.rb
app/models/scrape.rb
test/jobs/ingest_job_test.rb

This moves the scrape fulfillment to a job so that we're not blocking the main thread and can finish up the request quickly before managing transcoding and such.
Also now properly handles removed posts when returned from Hypatia without erroring out.
Closes #529

Move scrape callback ingestion to job
